// <auto-generated />
using System;
using CoffeeShop.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Persistence.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    [Migration("20230410063258_AddedMoreEmployees")]
    partial class AddedMoreEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Data.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("CoffeeShop.Data.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f256d5b7-7846-429f-9a92-0fd8716c7562"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            FirstName = "Sara",
                            IsDeveloper = false,
                            LastName = "Metroid"
                        },
                        new
                        {
                            Id = new Guid("69589598-33c0-4593-9792-4219e0fe553f"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            FirstName = "Jasmin",
                            IsDeveloper = true,
                            LastName = "Curtis"
                        },
                        new
                        {
                            Id = new Guid("b1ba54a4-690a-4419-b28b-90bcec91f64d"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            FirstName = "Aaa",
                            IsDeveloper = false,
                            LastName = "Metroid"
                        },
                        new
                        {
                            Id = new Guid("4d9fdefc-9bf8-469f-b4e9-3baf250ab0be"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            FirstName = "Bbb",
                            IsDeveloper = true,
                            LastName = "Curtis"
                        },
                        new
                        {
                            Id = new Guid("fab82060-46dd-43f9-bb31-ffc57afc1c4e"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            FirstName = "Anna",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = new Guid("34b8e70c-6a74-4af5-94d7-ac20b9817ef3"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            FirstName = "Julien",
                            IsDeveloper = true,
                            LastName = "Russell"
                        },
                        new
                        {
                            Id = new Guid("7d7f81c9-63cf-4aa4-a90c-70ca08d890e2"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            FirstName = "Ccc",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = new Guid("5963b3dc-18bb-4ac5-a3dc-05630f069098"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            FirstName = "Ddd",
                            IsDeveloper = true,
                            LastName = "Russell"
                        },
                        new
                        {
                            Id = new Guid("02ad0d59-5b78-4338-b0f6-b66cb71be4b1"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            FirstName = "Ben",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = new Guid("c4ce122c-d991-4474-a6ad-7fa7a52866f3"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            FirstName = "Alex",
                            IsDeveloper = true,
                            LastName = "Rider"
                        },
                        new
                        {
                            Id = new Guid("6fd18729-26df-4c99-ae01-dcfdc5810239"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            FirstName = "Eee",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = new Guid("d01e1d6b-3ff2-49e3-af9d-867e76c7f9c4"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            FirstName = "Fff",
                            IsDeveloper = true,
                            LastName = "Rider"
                        },
                        new
                        {
                            Id = new Guid("38d0787c-489d-4168-ba63-294882ed8808"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            FirstName = "Sophie",
                            IsDeveloper = false,
                            LastName = "Ramos"
                        },
                        new
                        {
                            Id = new Guid("595310ca-b66d-419b-964d-e73e1bf4a3b3"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            FirstName = "Yvonne",
                            IsDeveloper = true,
                            LastName = "Snider"
                        },
                        new
                        {
                            Id = new Guid("9b2fb5c9-0cfb-4bb3-8a28-45ef4a424f5c"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            FirstName = "Ggg",
                            IsDeveloper = false,
                            LastName = "Ramos"
                        },
                        new
                        {
                            Id = new Guid("7ac281aa-3289-45af-baa6-dbffeec37e0b"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            FirstName = "Hhh",
                            IsDeveloper = true,
                            LastName = "Snider"
                        },
                        new
                        {
                            Id = new Guid("7d8d3542-8e85-4b0d-9d43-9fdaf5b858fa"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            FirstName = "Julia",
                            IsDeveloper = false,
                            LastName = "Developer"
                        },
                        new
                        {
                            Id = new Guid("c617b0d8-3c2c-40eb-a233-3f561828634e"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            FirstName = "Thomas",
                            IsDeveloper = true,
                            LastName = "Huber"
                        },
                        new
                        {
                            Id = new Guid("5139920d-d071-4809-aa9a-07a7ffb4cc98"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            FirstName = "Iii",
                            IsDeveloper = false,
                            LastName = "Developer"
                        },
                        new
                        {
                            Id = new Guid("900217bf-931e-4fb8-acdf-c21a54c0de5a"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            FirstName = "Jjj",
                            IsDeveloper = true,
                            LastName = "Huber"
                        });
                });

            modelBuilder.Entity("CoffeeShop.Data.Entities.Employee", b =>
                {
                    b.HasOne("CoffeeShop.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CoffeeShop.Data.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
