// <auto-generated />
using System;
using CoffeeShop.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Persistence.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    [Migration("20230424164132_AddedTimeStamp")]
    partial class AddedTimeStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Data.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("CoffeeShop.Data.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("913dc0cc-cf3c-4682-9785-a1ac663e977f"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            FirstName = "Sara",
                            IsDeveloper = false,
                            LastName = "Metroid"
                        },
                        new
                        {
                            Id = new Guid("fc129ad8-158f-492a-8042-9c01af85df4b"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            FirstName = "Jasmin",
                            IsDeveloper = true,
                            LastName = "Curtis"
                        },
                        new
                        {
                            Id = new Guid("c535b761-0a98-4756-a5a8-b6bbf982c18f"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            FirstName = "Aaa",
                            IsDeveloper = false,
                            LastName = "Metroid"
                        },
                        new
                        {
                            Id = new Guid("cf90f97c-9e84-4d3c-a0cd-9db1292eb361"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6012"),
                            FirstName = "Bbb",
                            IsDeveloper = true,
                            LastName = "Curtis"
                        },
                        new
                        {
                            Id = new Guid("6a252fc9-4acc-4c15-8ada-3a07d944379a"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            FirstName = "Anna",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = new Guid("8eb682f4-01a0-478e-95ac-047928f41eae"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            FirstName = "Julien",
                            IsDeveloper = true,
                            LastName = "Russell"
                        },
                        new
                        {
                            Id = new Guid("898e6eae-4022-4e70-ba62-6b0dc11410ed"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            FirstName = "Ccc",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = new Guid("8b97a7a0-3c9f-40b0-9bce-48671c4d2038"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6013"),
                            FirstName = "Ddd",
                            IsDeveloper = true,
                            LastName = "Russell"
                        },
                        new
                        {
                            Id = new Guid("80dfa629-37c9-4e67-b974-3cd7d9fa0e98"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            FirstName = "Ben",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = new Guid("09c21161-f816-4866-8edf-1527c62aa5d6"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            FirstName = "Alex",
                            IsDeveloper = true,
                            LastName = "Rider"
                        },
                        new
                        {
                            Id = new Guid("b499b4ac-4882-489f-bf9d-b6c40699e36f"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            FirstName = "Eee",
                            IsDeveloper = false,
                            LastName = "Rockstar"
                        },
                        new
                        {
                            Id = new Guid("52355a13-481f-4332-877d-b202b9a77e4a"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6014"),
                            FirstName = "Fff",
                            IsDeveloper = true,
                            LastName = "Rider"
                        },
                        new
                        {
                            Id = new Guid("0d50fea4-0275-497d-a110-f6cf601bd069"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            FirstName = "Sophie",
                            IsDeveloper = false,
                            LastName = "Ramos"
                        },
                        new
                        {
                            Id = new Guid("044ccb1c-5703-4896-a95e-93b1ea6b6bd2"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            FirstName = "Yvonne",
                            IsDeveloper = true,
                            LastName = "Snider"
                        },
                        new
                        {
                            Id = new Guid("671b3a77-e0cc-4c96-ad4e-247b7e5f202e"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            FirstName = "Ggg",
                            IsDeveloper = false,
                            LastName = "Ramos"
                        },
                        new
                        {
                            Id = new Guid("208c4a40-579c-4137-8e2f-defe6301097f"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6015"),
                            FirstName = "Hhh",
                            IsDeveloper = true,
                            LastName = "Snider"
                        },
                        new
                        {
                            Id = new Guid("86e42885-ed16-4e98-907e-0e65caf482d4"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            FirstName = "Julia",
                            IsDeveloper = false,
                            LastName = "Developer"
                        },
                        new
                        {
                            Id = new Guid("996d0449-e96b-4a79-883c-d6bb7be82e74"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            FirstName = "Thomas",
                            IsDeveloper = true,
                            LastName = "Huber"
                        },
                        new
                        {
                            Id = new Guid("0f126378-3c29-4760-b511-f83c41617f01"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            FirstName = "Iii",
                            IsDeveloper = false,
                            LastName = "Developer"
                        },
                        new
                        {
                            Id = new Guid("61a880ab-c659-47c6-81c7-15dd9ade5776"),
                            DepartmentId = new Guid("5af7e850-75d0-42cf-aeba-996811fe6016"),
                            FirstName = "Jjj",
                            IsDeveloper = true,
                            LastName = "Huber"
                        });
                });

            modelBuilder.Entity("CoffeeShop.Data.Entities.Employee", b =>
                {
                    b.HasOne("CoffeeShop.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CoffeeShop.Data.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
